version: "3"
services:
  php:
    build: ./docker
    volumes:
      #- ./www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./src/app:/srv/app
    ports:
      - 9000:9000

  nginx:
    image: nginx:stable
    volumes:
      - ./src/app:/srv/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Super
      MYSQL_DATABASE: kata-api
    volumes:
      - ./initSQL:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8888:8080
